---
- name: Pull docker image of sci_calc
  hosts: all
  tasks:

    - name: Start docker service
      service:
        name: docker
        state: started
        
    - name: pull docker image
      shell: docker pull vivekdocker2309/spe_mini_project
      
    - name: running container
      shell: docker run -it -d vivekdocker2309/spe_mini_project
